name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      # 2. Configure Git for GitHub Actions
      - name: Configure Git
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      # 3. Prepare the deployment directory
      - name: Prepare deployment directory
        run: |
          mkdir -p ../deploy  # Create a temporary deployment directory
          cp -r * ../deploy/  # Copy all files to the temporary directory

      # 4. Switch to the 'gh-pages' branch and pull latest changes
      - name: Switch to gh-pages and pull latest changes
        run: |
          git checkout gh-pages || git checkout --orphan gh-pages
          git pull origin gh-pages || true  # Pull latest changes to avoid conflicts
          git rm -rf . || true  # Remove all files in the current branch
          git clean -fxd  # Clean untracked files

      # 5. Copy deployment files to the 'gh-pages' branch
      - name: Copy files to gh-pages
        run: |
          cp -r ../deploy/* .  # Copy files from the temporary directory to the current branch
          rm -rf ../deploy  # Remove the temporary directory

      # 6. Commit and push changes to GitHub Pages
      - name: Commit and push changes
        run: |
          git add .
          git commit -m "Deploy updates from $(date)" || echo "No changes to commit"
          git pull origin gh-pages || true  # Pull latest changes to avoid conflicts

          git push origin gh-pages || true 
