name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

    #   Github setup
      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
      
    #    Deploying
      - name: Deploy to GitHub Pages
        run: |
          # Switch to gh-pages branch or create a new orphan branch
          git fetch origin gh-pages
          git checkout gh-pages || git checkout --orphan gh-pages

          # Remove old files and copy new files
          git reset --hard
          git clean -fdx
          cp -r $(ls -A | grep -v .git) ../temp-deploy
          rm -rf *
          cp -r ../temp-deploy/* .
          rm -rf ../temp-deploy

          # Commit and push changes
          git add .
          if git diff-index --quiet HEAD; then
            echo "No changes to deploy."
          else
            git commit -m "Deploy updates from $(date)"
            git push -f origin gh-pages
          fi
